import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PageFrame } from "@/components/site-shell";
import { StoryMeta } from "@/components/story";
import { getArticleBySlug, listPublishedArticles } from "@/lib/data";
import { authorSlug, formatPublishDate, markdownToHtml, readLabel } from "@/lib/format";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const a=await getArticleBySlug(slug).catch(()=>null);if(!a)return{};return{title:a.meta_title||a.title,description:a.meta_description||a.excerpt,alternates:{canonical:"/blog/"+a.slug+"/"},openGraph:{title:a.meta_title||a.title,description:a.meta_description||a.excerpt,type:"article",images:a.cover_image_url?[a.cover_image_url]:undefined}}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const article=await getArticleBySlug(slug).catch(()=>null);if(!article)notFound();const related=(await listPublishedArticles().catch(()=>[])).filter(a=>a.id!==article.id).slice(0,3);const aSlug=authorSlug(article.author);return <PageFrame current="blog"><article className="article"><header className="article-header"><div className="article-label">{article.category||"Journal"}</div><h1>{article.title}</h1>{article.excerpt&&<p className="article-deck">{article.excerpt}</p>}<div className="article-byline"><div><span>BY</span>{aSlug?<a href={"/authors/"+aSlug+"/"}>{article.author}</a>:<strong>{article.author}</strong>}</div><div><span>PUBLISHED</span><strong>{formatPublishDate(article.published_at)}</strong></div><div><span>READ TIME</span><strong>{readLabel(article.read_time_minutes)}</strong></div></div></header>{article.cover_image_url&&<figure className="article-hero"><img src={article.cover_image_url} alt=""/></figure>}<div className="article-layout"><aside className="article-rail"><span>MIIDASU JOURNAL</span><a href="/blog/">All stories ↗</a></aside><div className="article-body" dangerouslySetInnerHTML={{__html:markdownToHtml(article.content||"")}}/></div></article>{related.length>0&&<section className="related"><div className="section-rule"><h2>Keep reading</h2><a href="/blog/">Journal ↗</a></div><div className="story-grid compact">{related.map(a=><article className="story-card" key={a.id}><StoryMeta article={a}/><h3><a href={"/blog/"+a.slug+"/"}>{a.title}</a></h3><p>{a.excerpt}</p></article>)}</div></section>}</PageFrame>}
